### ISSUE TITLE
Upgrade gradle version

### ISSUE THREAD

**Issue by AizazAZ** [nohana/Laevatein#22]
Cannot import into Android Studio. Please upgrade Gradle version to 1.0

**Comment by AizazAZ** [comment]
Tried to import it in Idea 14 but still failed.

**Comment by AizazAZ** [comment]
pretty useless without updated gradle wrapper. Couldn't import it in Inteli J, Android Studio although tried to update wrapper. it didn't load src files...

**Comment by KeithYokoma** [comment]
We are now using Gradle 2.2.1.

**Comment by AizazAZ** [comment]
https://github.com/AizazAZ/Android-Ultra-Photo-Selector

**Comment by AizazAZ** [comment]
Well thanks..

**Comment by KeithYokoma** [comment]
I think this issue is no longer a problem now. Close it for now.
