### ISSUE TITLE
NoClassDefFoundError が発生する

### ISSUE THREAD

**Issue by rnitame** [nohana/Laevatein#65]
AppCompatActivity を継承した Activity の中でボタンをクリックした際に、以下のコードで Laevatein を使おうとしています。

```kt
Laevatein.from(this)
                .choose(MimeType.of(MimeType.JPEG))
                .resume(selectedImages)
                .quality(1000, 1000)
                .count(1, 10)
                .capture(true)
                .enableSelectedView(true)
                .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)
                .forResult(RESULT_IMAGE)
```

ですが、起動せずに以下のエラーが吐かれて強制終了します。

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/ActionBarActivity;
at com.laevatein.Laevatein.from(Laevatein.java:63)
```

サンプルは問題なく起動できたのですが、何か記述が足りないのでしょうか…？

**Comment by hiroyuki-seto** [comment]
当方では再現できていませんが、恐らく最新support libraryでActionBarActivityが削除されたことにLaevateinが追従できていないことが原因だと思われます。
修正してリリースいたしますので少々お待ち下さい！

**Comment by hiroyuki-seto** [comment]
すみません、上記のActionBarActiivty削除問題には対応済みでした。
Laevateinのバージョンはいくつをお使いでしょうか？

**Comment by rnitame** [comment]
1.0.4 です！

**Comment by hiroyuki-seto** [comment]
お手数ですがLaevateinをバージョンアップいただき、Ver2.1.0以降をお使いいただくとこちらの問題は再現しなくなるかと思われます(現在の最新版は2.1.2になっております)
READMEの情報が更新されておらず申し訳ありません..

**Comment by rnitame** [comment]
おお！解決しました！ありがとうございます！

**Comment by hiroyuki-seto** [comment]
🎉
