### ISSUE TITLE
Stop using AppGlideModule

### ISSUE THREAD

**Issue by hiroyuki-seto** [nohana/Laevatein#73]
http://bumptech.github.io/glide/doc/configuration.html#avoid-appglidemodule-in-libraries
😇 

> This does mean that libraries won’t be able to use Glide’s generated API, but loads with RequestOptions will still work just fine (see the options page for examples).

We should use RequestOptions instead of AppGlideModule in this library.

**Comment by cookych** [comment]
Sorry, I'm modify it to use RequestOptions. 🙇
