### ISSUE TITLE
Glide Library issue 

### ISSUE THREAD

**Issue by koradiyadhaval** [nohana/Laevatein#89]
I am using glide latest version 4.10.0 and your library is using old version of 4.9.0 so i am facing few crashed every time when i open the image pickerview.
Please see the log for more details and suggest you please update Glide library version 4.10.0 because internal glide conflict some feature inside 4.9.0 and 4.10.0

12-26 11:54:40.966 14169-14340/com.dancero E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb8dae380
12-26 11:54:41.183 14169-14169/com.dancero E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dancero, PID: 14169
    java.lang.NoSuchMethodError: No virtual method fitCenter()Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.dancero-2/base.apk)

**Comment by mrtry** [comment]
@koradiyadhaval
Thank you for Issue!
I'll update it by the end of January. 🙏

**Comment by mrtry** [comment]
Sorry, I'll do it next week.

**Comment by mrtry** [comment]
@koradiyadhaval
Released `3.0.1`.
Sorry for being late. :pray:
https://repo1.maven.org/maven2/jp/co/nohana/Laevatein/
